const products = [
  {
    name: "Product 1",
    category: "skincare",
    price: 30000,
    image: "./images/S1.png",
  },
  {
    name: "Product 2",
    category: "skincare",
    price: 37000,
    image: "./images/S2.png",
  },
  {
    name: "Product 3",
    category: "makeup",
    price: 21000,
    image: "./images/S3.png",
  },
  {
    name: "Product 4",
    category: "lipstick",
    price: 9700,
    image: "./images/S4.png",
  },
  {
    name: "Product 5",
    category: "hairbody",
    price: 24000,
    image: "./images/S5.png",
  },
  {
    name: "Product 6",
    category: "skincare",
    price: 30000,
    image: "./images/S6.png",
  },
  {
    name: "Product 7",
    category: "makeup",
    price: 21000,
    image: "./images/S7.png",
  },
  {
    name: "Product 8",
    category: "hairbody",
    price: 8000,
    image: "./images/S8.png",
  },
  {
    name: "Product 9",
    category: "lipstick",
    price: 4500,
    image: "./images/S9.png",
  },
  {
    name: "Product 10",
    category: "lipstick",
    price: 7600,
    image: "./images/S10.png",
  },
  {
    name: "Product 11",
    category: "skincare",
    price: 8700,
    image: "./images/S11.png",
  },
  {
    name: "Product 12",
    category: "makeup",
    price: 23500,
    image: "./images/S12.png",
  },
  {
    name: "Product 13",
    category: "hairbody",
    price: 40000,
    image: "./images/S13.png",
  },
  {
    name: "Product 14",
    category: "skincare",
    price: 4500,
    image: "./images/S14.png",
  },
  {
    name: "Product 15",
    category: "lipstick",
    price: 5000,
    image: "./images/S15.png",
  },
  {
    name: "Product 16",
    category: "hairbody",
    price: 11000,
    image: "./images/S16.png",
  },
  {
    name: "Product 17",
    category: "makeup",
    price: 9000,
    image: "./images/S17.png",
  },
  {
    name: "Product 18",
    category: "skincare",
    price: 6500,
    image: "./images/S18.png",
  },
  {
    name: "Product 19",
    category: "hairbody",
    price: 37700,
    image: "./images/S19.png",
  },
  {
    name: "Product 20",
    category: "skincare",
    price: 23000,
    image: "./images/S20.png",
  },
  {
    name: "Product 21",
    category: "makeup",
    price: 12000,
    image: "./images/S21.png",
  },
  {
    name: "Product 22",
    category: "skincare",
    price: 20000,
    image: "./images/S22.png",
  },
];

module.exports = products;
